apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-beeclass-web-release-fe
  namespace: beeclass
  labels:
    app: dev-beeclass-web-release-fe
    env: dev
spec:
  selector:
    matchLabels:
      app: dev-beeclass-web-release-fe
      env: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dev-beeclass-web-release-fe
        env: dev
    spec:
      imagePullSecrets:
      - name: broodreg
      containers:
      - image: brood.azurecr.io/tungpx/beeclass_web_release:dev
        imagePullPolicy: Always
        name: dev-beeclass-web-release-fe
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        resources:
          requests:
            memory: 50Mi
            cpu: 20m
          limits:
            memory: 100Mi
            cpu: 50m
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
      nodeSelector:
        pool: internalApp
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "internal"
        effect: "NoSchedule"
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-beeclass-web-release-fe
  namespace: beeclass
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - dev-beeclass-web-release-fe.aks-dev.mb-innovationlab.com
    secretName: tls-dev-beeclass-web-release-fe
  rules:
  - host: dev-beeclass-web-release-fe.aks-dev.mb-innovationlab.com
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: dev-beeclass-web-release-fe
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dev-beeclass-web-release-fe
  namespace: beeclass
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: dev-beeclass-web-release-fe
    env: dev

