apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-beeclass-web-release
  namespace: beeclass
  labels:
    app: beeclass-web-release
    env: prod
spec:
  selector:
    matchLabels:
      app: beeclass-web-release
      env: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: beeclass-web-release
        env: prod
    spec:
      imagePullSecrets:
      - name: broodreg
      containers:
      - image: brood.azurecr.io/tungpx/beeclass_web_release:prod-5
        imagePullPolicy: Always
        name: frontend
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        resources:
          requests:
            memory: 50Mi
            cpu: 20m
          limits:
            memory: 100Mi
            cpu: 50m
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
      nodeSelector:
        pool: internalApp
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "internal"
        effect: "NoSchedule"
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prod-beeclass-web-release
  namespace: beeclass
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: prod-beeclass-web-release-fe.uat.mb-innovationlab.com
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: prod-beeclass-web-release
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: prod-beeclass-web-release
  namespace: beeclass
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: beeclass-web-release
    env: prod
